"""pathogen module

Revision ID: 502fb0d93b4c
Revises: 267e785fd08c
Create Date: 2026-08-28 02:57:22.702784

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '502fb0d93b4c'
down_revision: Union[str, Sequence[str], None] = '267e785fd08c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pathogens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('scientific_name', sa.String(length=200), nullable=True),
    sa.Column('gram_stain', sa.String(length=20), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pathogens_id'), 'pathogens', ['id'], unique=False)
    op.create_index(op.f('ix_pathogens_name'), 'pathogens', ['name'], unique=True)
    op.drop_table('analysisis')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analysisis',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sample_image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('analysisis_pkey'))
    )
    op.drop_index(op.f('ix_pathogens_name'), table_name='pathogens')
    op.drop_index(op.f('ix_pathogens_id'), table_name='pathogens')
    op.drop_table('pathogens')
    # ### end Alembic commands ###
