"""patient module

Revision ID: 56c107356f5e
Revises: 89377a54aba8
Create Date: 2026-08-27 14:30:34.235139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '56c107356f5e'
down_revision: Union[str, Sequence[str], None] = '89377a54aba8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'date_of_birth',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###
