"""patient module

Revision ID: 61139d8b93e7
Revises: 7742a45ce7e2
Create Date: 2026-08-27 14:18:26.971803

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61139d8b93e7'
down_revision: Union[str, Sequence[str], None] = '7742a45ce7e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('date_of_birth', sa.Date(), nullable=False))
    op.alter_column('patients', 'age',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'age',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('patients', 'date_of_birth')
    # ### end Alembic commands ###
