"""patient module

Revision ID: 7742a45ce7e2
Revises: c1ee2755e090
Create Date: 2026-08-27 13:06:11.490027

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7742a45ce7e2'
down_revision: Union[str, Sequence[str], None] = 'c1ee2755e090'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('patients', 'patient_code',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_unique_constraint(None, 'patients', ['patient_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='unique')
    op.alter_column('patients', 'patient_code',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
