"""antibiotic module

Revision ID: abd4ef33826f
Revises: 56c107356f5e
Create Date: 2026-08-28 04:32:53.298417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abd4ef33826f'
down_revision: Union[str, Sequence[str], None] = '56c107356f5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_pathogens_id'), table_name='pathogens')
    op.drop_index(op.f('ix_pathogens_name'), table_name='pathogens')
    op.drop_table('pathogens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pathogens',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=150), autoincrement=False, nullable=False),
    sa.Column('scientific_name', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('gram_stain', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pathogens_pkey'))
    )
    op.create_index(op.f('ix_pathogens_name'), 'pathogens', ['name'], unique=True)
    op.create_index(op.f('ix_pathogens_id'), 'pathogens', ['id'], unique=False)
    # ### end Alembic commands ###
