"""antibiotic module

Revision ID: c85d00342190
Revises: 4be82b23c0f0
Create Date: 2026-08-28 04:43:51.957630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c85d00342190'
down_revision: Union[str, Sequence[str], None] = '4be82b23c0f0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('antibiotics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('class_name', sa.String(length=150), nullable=True),
    sa.Column('route', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_antibiotics_id'), 'antibiotics', ['id'], unique=False)
    op.create_index(op.f('ix_antibiotics_name'), 'antibiotics', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_antibiotics_name'), table_name='antibiotics')
    op.drop_index(op.f('ix_antibiotics_id'), table_name='antibiotics')
    op.drop_table('antibiotics')
    # ### end Alembic commands ###
